### ISSUE TITLE
Command to train and evaluate TSM ResNet-18/ResNet-50 baselines

### ISSUE THREAD

**Issue by 17Skye17** [CVIR/TCL#5]
Hi,
Thanks for sharing this nice repo : )!
Could you share the command to train and evaluate the TSM ResNet-18/ResNet-50 baselines?

Thank you!

**Comment by omchakrabarty** [comment]
You can find it in the official TSM repo: `https://github.com/mit-han-lab/temporal-shift-module`

**Comment by 17Skye17** [comment]
Helps me. Thank you for your reply.
