### ISSUE TITLE
Question about resnet.py

### ISSUE THREAD

**Issue by KittyStore** [CVIR/TCL#8]
Thank you for your perfect work on the paper Semi-Supervised Action Recognition with Temporal Contrastive Learning.

I want to know what is the function of the parameter 'unlabeled'?

```
def _forward_impl(self, x, unlabeled=False):
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        #print("size of x is layer1 is {}".format(x.size()))
        x = self.layer1(x, unlabeled)
        #print("size of x is layer2 is {}".format(x.size()))

        x = self.layer2(x, unlabeled)
        #print("size of x is layer3 is {}".format(x.size()))

        x = self.layer3(x, unlabeled)
        #print("size of x is layer4 is {}".format(x.size()))

        x = self.layer4(x, unlabeled)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x
```
In class BasicBlock , the forward function just has two parameters but doesn't have the parameter 'unbeled' .So like 'x = self.layer1(x, unlabeled)' will be wrong.

**Comment by KittyStore** [comment]
I have known the reason, and I will close this question. Thanks.

**Comment by Serendipity-LC** [comment]
> I have known the reason, and I will close this question. Thanks.

Hi! What is the purpose of the parameter 'unlabeled' in the function _forward_impl? This parameter seems to be useless in resnet.
