### ISSUE TITLE
Another Question about In_place TSM and Residual TSM

### ISSUE THREAD

**Issue by KittyStore** [CVIR/TCL#9]
In TCL, do you use In_place TSM instead of Residual TSM?
```
class make_block_temporal(nn.Module):
    def __init__(self, stage, this_segment=3,n_div=8, second_segments=2):
        super(make_block_temporal, self).__init__()
        self.blocks = nn.ModuleList(list(stage.children()))
        self.second_segments = second_segments
        print('=> Processing stage with {} blocks'.format(len(self.blocks)))
        self.temporal_shift = TemporalShift(n_segment=this_segment, n_div=n_div, second_segments= self.second_segments)
#        for i, b in enumerate(self.blocks):
 #           self.blocks[i]= nn.Sequential(b)
    def forward(self,x,unlabeled=False):
        for i, b in enumerate(self.blocks):
            x= self.temporal_shift(x,unlabeled)
            x = self.blocks[i](x)  #just use x, without unlabeled parameters
        return x

class make_blockres_temporal(nn.Module):
    def __init__(self, stage, this_segment=3,n_div=8, n_round=1, second_segments=2):
        super(make_blockres_temporal, self).__init__()
        self.blocks = nn.ModuleList(list(stage.children()))
        self.second_segments = second_segments
        self.n_round = n_round
        print('=> Processing stage with {} blocks'.format(len(self.blocks))) 
        self.temporal_shift = TemporalShift(n_segment=this_segment, n_div=n_div, second_segments=self.second_segments)
   #     for i, b in enumerate(self.blocks):
  #          self.blocks[i]= nn.Sequential(b)
 #           print(self.blocks[i])

    def forward(self,x,unlabeled=False):
        #print("make_block_res_temporal_called")
        for i, b in enumerate(self.blocks):
            #print(x.size())
            if i% self.n_round == 0:
                #print("size of x is {}".format(x.size()))
                x= self.temporal_shift(x,unlabeled)
            x = self.blocks[i](x)  #just use x, without unlabeled parameters
        return x
```
You change the function 'make_blockres_temporal', and it works as the function 'make_block_temporal'.

**Comment by Griffintaur** [comment]
We didn't use Inplace shifting in our experiments. The authors of TSM mentioned that there were some out-of-order errors being reported when performing parallel computing using the Inplace approach. see the comment at https://github.com/CVIR/TCL/blob/master/ops/temporal_shift.py#L38.
For the second part of the question, all our experiments were performed where Shifting used to take place as BlockRes level rather than block level. These functions were provided by TSM paper (see the method at https://github.com/mit-han-lab/temporal-shift-module/blob/master/ops/temporal_shift.py#L97) which we incorporated as python classes.

**Comment by KittyStore** [comment]
Thank you for your apply.What I mean is that I don't think there are some different things between your implements of 'make_block_temporal' and 'make_blockres_temporal'(maybe just add parameter 'n_round').

**Comment by KittyStore** [comment]
Thank you for your reply.What I mean is that I don't think there are some difference between your implements of 'make_block_temporal' and 'make_blockres_temporal'(maybe just add parameter 'n_round').  

From your implements of 'make_blockres_temporal',I think you just use the In-place TSM instead of Residual TSM,which maybe harm the final results.

In paper TSM , the author points out that the effect of Resudual TSM is better than that of In-place TSM.

**Comment by Griffintaur** [comment]
`n_round` is an important parameter that determines where and how many temporal shifts will be introduced.
We are not using in place if you look carefully the default parameter for `inplace` in the `TemporalShift` class is kept as `False`.

**Comment by Griffintaur** [comment]
`n_round` is an important parameter that determines where and how many temporal shifts will be introduced.
We are not using in place if you look carefully the default parameter for `inplace` in the `TemporalShift` class is kept as `False`
